// Source: Designs/NARICARE PRIVACY POLICY.pdf + NARICARE TERMS OF SERVICE.pdf (verbatim, pending legal confirmation)
export type LegalBlock =
  | { h: string }
  | { sub: string }
  | { p: string; bold?: boolean }
  | { ul: string[] }
  | { ol: string[] };

export interface LegalDoc {
  title: string;
  dates: string[];
  blocks: LegalBlock[];
}

const ADDRESS = 'Sagex, 47-10-6 Sripada Diamond Towers, Shop 11, 2nd Floor, Diamond Park, Visakhapatnam-530016, Andhra Pradesh, India';

export const PRIVACY_POLICY: LegalDoc = {
  title: 'Privacy Policy',
  dates: ['Effective Date: January 15, 2025', 'Last Updated: January 15, 2025'],
  blocks: [
    { h: '1. Introduction' },
    { p: 'Sagex (a partnership firm registered under the Indian Partnership Act, 1932, with principal place of business at 47-10-6 Sripada Diamond Towers, Shop 11, 2nd Floor, Diamond Park, Visakhapatnam-530016, Andhra Pradesh, India) ("Company," "we," "us," or "NariCare") operates a digital health platform specializing in maternal and infant care, specifically focused on breastfeeding support and postpartum wellness.' },
    { p: 'This Privacy Policy explains how we collect, use, process, and protect your personal information when you use our mobile application, website, and related services (collectively, the "Platform").' },
    { p: 'By using our Platform, you consent to the data practices described in this Policy.', bold: true },

    { h: '2. Information We Collect' },
    { sub: '2.1 Information You Provide Directly' },
    { p: 'Account and Profile Information:', bold: true },
    { ul: ['Name, email address, phone number', 'Date of birth, location (city/state)', 'Profile photographs (optional)', 'Account preferences and settings'] },
    { p: 'Health and Maternal Care Information:', bold: true },
    { ul: ['Pregnancy status, due dates, birth details', 'Baby information (name, birth date, weight, developmental milestones)', 'Breastfeeding goals, challenges, and preferences', 'Medical history relevant to maternal and infant care (voluntary)', 'Current medications and supplements (voluntary)'] },
    { p: 'Health Tracking Data:', bold: true },
    { ul: ['Feeding records: timing, duration, breast preference, pain assessment', 'Pumping sessions: volume, duration, comfort levels', 'Diaper monitoring: type, frequency, characteristics', 'Growth tracking: weight, height, head circumference measurements', 'Sleep patterns: duration, quality, timing', 'Emotional wellness: mood indicators, postpartum screening responses'] },
    { p: 'Communication Data:', bold: true },
    { ul: ['Messages with healthcare professionals through the Platform', 'Consultation notes and follow-up communications', 'Community forum posts and interactions', 'Customer support inquiries and feedback'] },
    { sub: '2.2 Information Collected Automatically' },
    { p: 'Device and Technical Information:', bold: true },
    { ul: ['Device type, model, operating system version', 'IP address and general geographic location', 'Mobile network information and carrier', 'Device identifiers and advertising IDs'] },
    { p: 'Platform Usage Analytics:', bold: true },
    { ul: ['Features accessed and time spent on different sections', 'Navigation patterns and user interface interactions', 'Search queries and content preferences', 'App performance data and crash reports'] },
    { p: 'Cookies and Tracking Data:', bold: true },
    { ul: ['Session cookies for platform functionality', 'Analytics cookies for usage optimization', 'Preference cookies for personalization', 'Security cookies for fraud prevention'] },
    { sub: '2.3 Information from Third Parties' },
    { p: 'Healthcare Professionals:', bold: true },
    { ul: ['Notes and assessments from consultations conducted through the Platform', 'Referral information and care coordination data', 'Progress reports and treatment recommendations'] },
    { p: 'Payment Processors:', bold: true },
    { ul: ['Transaction data and payment verification (limited to necessary information)', 'Billing address and payment method details'] },

    { h: '3. How We Use Your Information' },
    { sub: '3.1 Core Platform Services' },
    { p: 'Personalized Health Support:', bold: true },
    { ul: ['Provide customized recommendations based on your health profile', 'Generate insights from your tracking data and health patterns', 'Connect you with appropriate healthcare professionals', 'Deliver targeted educational content and resources'] },
    { p: 'AI-Powered Assistance:', bold: true },
    { ul: ['Process your queries to provide relevant, evidence-based responses', 'We only use your identifiable data to improve AI with your explicit opt-in; otherwise we use de-identified aggregates', 'Customize chat interactions based on your specific situation', 'Improve AI response accuracy through machine learning on anonymized data'] },
    { p: 'Professional Care Coordination:', bold: true },
    { ul: ['Share relevant information with healthcare providers (with consent)', 'Maintain continuity of care across multiple consultations', 'Facilitate communication between different care providers', 'Track progress and outcomes across your care journey'] },
    { sub: '3.2 Platform Operations and Improvement' },
    { p: 'Service Optimization:', bold: true },
    { ul: ['Analyze usage patterns to improve platform functionality', 'Identify and resolve technical issues and bugs', 'Develop new features based on user needs and feedback', 'Conduct quality assurance and performance monitoring'] },
    { p: 'Communication and Support:', bold: true },
    { ul: ['Send important service updates and security notifications', 'Provide customer support and technical assistance', 'Deliver educational content and health tips', 'Facilitate community interactions and peer support'] },
    { sub: '3.3 Legal and Safety Obligations' },
    { p: 'Regulatory Compliance:', bold: true },
    { ul: ['Meet requirements under Indian healthcare and data protection laws', 'Respond to lawful requests from government authorities', 'Maintain records for audit and regulatory purposes', 'Ensure platform security and user safety'] },
    { p: 'Fraud Prevention and Security:', bold: true },
    { ul: ['Detect and prevent fraudulent activities', 'Verify user identities and payment information', 'Monitor for suspicious or harmful behavior', 'Protect platform integrity and user security', 'Report notifiable cybersecurity incidents to CERT-In within 6 hours of detection and notify affected users and the Data Protection Board of India (when operational) as required by law'] },

    { h: '4. Information Sharing and Disclosure' },
    { sub: '4.1 Healthcare Professionals' },
    { p: 'With Your Explicit Consent, we share relevant health information with licensed healthcare professionals who provide services through our Platform:' },
    { p: 'Lactation Consultants (IBCLC/Certified):', bold: true },
    { ul: ['Breastfeeding tracking data and challenges', "Baby's feeding patterns and growth metrics", 'Maternal health factors affecting lactation', 'Previous consultation history for continuity'] },
    { p: 'Registered Nutritionists/Dietitians:', bold: true },
    { ul: ['Postpartum nutrition needs and dietary information', 'Health conditions affecting nutritional requirements', 'Weight and wellness goal tracking data', 'Food preferences and restrictions'] },
    { p: 'Licensed Mental Health Professionals:', bold: true },
    { ul: ['Postpartum mood and wellness screening results', 'Emotional check-in data and mental health indicators', 'Support needs assessment and progress tracking', 'Crisis intervention data (if applicable)'] },
    { p: 'Other Specialists (Sleep Coaches, Fitness Instructors):', bold: true },
    { ul: ['Relevant health data specific to their area of expertise', 'Progress tracking information for their services', 'Safety considerations and contraindications'] },
    { sub: '4.2 Service Providers and Business Partners' },
    { p: 'We engage trusted third-party service providers who assist with platform operations:' },
    { p: 'Technology Infrastructure:', bold: true },
    { ul: ['Cloud hosting providers (with data encryption and appropriate safeguards)', 'Database management services (with security and access controls)', 'Content delivery networks for optimal performance'] },
    { p: 'Communication Services:', bold: true },
    { ul: ['Email service providers for notifications and communications', 'SMS/messaging services for alerts and verifications', 'Audio/video consultation platforms for telehealth services (encrypted)', 'Push notification services for mobile app alerts'] },
    { p: 'Payment and Financial:', bold: true },
    { ul: ['Payment processors (receiving only transaction-necessary data)', 'Billing and invoicing services (limited to payment-related information)', 'Fraud detection services (for transaction security)'] },
    { p: 'Analytics and Research:', bold: true },
    { ul: ['Performance monitoring services (receiving only anonymized data)', 'Academic research institutions (for anonymized maternal health research with robust de-identification and no re-identification attempts)', 'Healthcare outcome research (with aggregated, de-identified data only)'] },
    { sub: '4.3 Legal and Regulatory Disclosures' },
    { p: 'We may disclose information when required by Indian law or when necessary to:' },
    { ul: ['Comply with court orders, legal processes, or regulatory requirements', 'Respond to lawful requests from government authorities', 'Protect our rights, property, and legal interests', 'Ensure user safety and prevent harm', 'Investigate suspected fraud or violations of our Terms'] },
    { sub: '4.4 Business Transactions' },
    { p: 'In the event of a merger, acquisition, or sale of assets:' },
    { ul: ['Users will be notified in advance of any ownership changes', 'Equivalent privacy protections will be maintained by the acquiring entity', 'Opt-out options will be provided if privacy practices change materially', 'Data transfer will comply with applicable Indian laws'] },

    { h: '5. Data Security and Protection' },
    { sub: '5.1 Technical Safeguards' },
    { p: 'Encryption:', bold: true },
    { ul: ['Data in transit: TLS 1.3 encryption for all communications', 'Data at rest: AES-256 encryption for stored information', 'Database encryption: Field-level encryption for sensitive health data', 'Backup encryption: All backup systems use strong encryption'] },
    { p: 'Access Controls:', bold: true },
    { ul: ['Role-based access permissions limiting data access to authorized personnel', 'Multi-factor authentication for all administrative accounts', 'Regular access reviews and audits to ensure appropriate permissions', 'Automated session timeouts for inactive users'] },
    { p: 'Infrastructure Security:', bold: true },
    { ul: ['SOC 2 Type II compliant cloud infrastructure providers', 'Regular penetration testing by independent security firms', 'Continuous security monitoring and threat detection', 'Incident response procedures for security events'] },
    { sub: '5.2 Organizational Safeguards' },
    { p: 'Staff Training:', bold: true },
    { ul: ['Mandatory privacy and security training for all employees', 'Healthcare data handling certification for relevant staff', 'Regular updates on data protection regulations and best practices', 'Confidentiality agreements for all personnel with data access'] },
    { p: 'Operational Procedures:', bold: true },
    { ul: ['Data minimization practices collecting only necessary information', 'Regular security audits and vulnerability assessments', 'Vendor security assessments for all third-party service providers', 'Incident response plans with clear escalation procedures'] },
    { sub: '5.3 Health Information Protection' },
    { p: 'Enhanced Protections for Sensitive Health Data:', bold: true },
    { ul: ['Separate encryption keys for health information', 'Restricted access on a strict need-to-know basis', 'Audit logging for all health data access and modifications', 'Regular compliance assessments against healthcare data protection standards'] },

    { h: '6. Data Retention and Deletion' },
    { sub: '6.1 Retention Periods' },
    { p: 'Active User Accounts:', bold: true },
    { ul: ['Personal information: Retained while account is active and for 3 years after last activity', 'Teleconsult records and logs: Minimum 3 years (or longer where required by law/claims)', 'Health tracking data: Default 3 years from last activity, after which we anonymize', 'Payment information: Retained per Indian tax and GST laws'] },
    { p: 'Inactive Accounts:', bold: true },
    { ul: ['Account reminder notifications sent at 1 year and 2 years of inactivity', 'Account marked for deletion after 3 years of complete inactivity', 'Data deletion process initiated unless legal retention requirements apply'] },
    { sub: '6.2 Data Deletion Process' },
    { p: 'User-Initiated Deletion:', bold: true },
    { ul: ['Immediate removal of data not subject to legal retention requirements', 'Anonymization of data that must be retained for regulatory compliance', 'Confirmation notification sent upon completion of deletion process', 'Restoration period of 30 days for accidental deletion requests'] },
    { p: 'Automatic Deletion:', bold: true },
    { ul: ['System-initiated deletion of expired data based on retention schedules', 'Secure deletion methods ensuring data cannot be recovered', 'Deletion logging for audit and compliance purposes'] },
    { sub: '6.3 Legal and Medical Record Retention' },
    { p: 'Telemedicine records: Minimum 3 years, unless extended by law or ongoing disputes. Certain other information may be retained longer due to:' },
    { ul: ['Indian medical record laws requiring retention of health information', 'Tax and financial regulations for payment and billing records', 'Legal proceedings or investigations that may require data preservation', 'Vital health information that may be important for future care'] },

    { h: '7. Your Privacy Rights' },
    { sub: '7.1 Access and Control Rights' },
    { p: 'Right to Access:', bold: true },
    { ul: ['Request copies of all personal information we hold about you', 'Receive information about how your data is being processed', 'Obtain details about data sharing and third-party access', 'Access your data through secure self-service options in your account'] },
    { p: 'Right to Correction:', bold: true },
    { ul: ['Update inaccurate personal or health information', 'Complete incomplete profiles and health records', 'Modify preferences and communication settings', 'Correct errors in tracking data and health records'] },
    { p: 'Right to Deletion:', bold: true },
    { ul: ['Request removal of personal information (subject to legal retention requirements)', 'Anonymize health data that cannot be fully deleted for medical reasons', 'Close account and cease all data processing for marketing purposes', 'Selective deletion of specific data categories where legally permissible'] },
    { sub: '7.2 Data Portability and Transfer' },
    { p: 'Data Export:', bold: true },
    { ul: ['Download your information in machine-readable formats (JSON, CSV)', 'Transfer data to other healthcare platforms or providers', 'Receive complete records of consultations and health tracking', 'Export capabilities available through account settings', 'Consent Manager integration (as per DPDP Act Section 13) as an optional route for data portability requests'] },
    { sub: '7.3 Communication and Marketing Controls' },
    { p: 'Consent Management:', bold: true },
    { ul: ['Opt out of marketing communications while maintaining essential service notifications', 'Choose communication channels (email, SMS, push notifications, in-app)', 'Control frequency of non-essential communications', 'Maintain safety notifications regardless of other communication preferences'] },
    { p: 'Consent Withdrawal:', bold: true },
    { ul: ['Withdraw consent for specific data processing activities', 'Modify data sharing permissions with healthcare providers', 'Change research participation preferences', 'Update privacy preferences at any time through account settings'] },
    { sub: '7.4 Exercising Your Rights' },
    { p: 'How to Make Requests:', bold: true },
    { ol: ['Through your account settings for basic changes and data access', 'Email privacy@naricare.com for complex requests requiring manual review', 'Written request to our physical address for formal legal requests', 'Through customer support for assistance with privacy-related questions'] },
    { p: 'Response Timeline:', bold: true },
    { ul: ['Immediate processing for account setting changes', 'Within 30 days for data access and correction requests', 'Within 45 days for complex deletion or portability requests', 'Extensions communicated if additional time is required due to request complexity'] },

    { h: '8. Special Privacy Considerations' },
    { sub: '8.1 Minors and Family Information' },
    { p: "Children's Privacy: Accounts must be created by persons 18 years or older. Child profiles (under 18) may be added by a parent/guardian with verifiable parental consent. We do not profile or serve targeted advertising to children.", bold: true },
    { p: 'Sensitive Family Information:', bold: true },
    { ul: ['Partner/spouse information collected only with explicit consent', 'Family health history processed with additional security measures', 'Household data sharing controlled by primary account holder', 'Child safety protections in community features and communications'] },
    { sub: '8.2 Mental Health Information' },
    { p: 'Enhanced Protections:', bold: true },
    { ul: ['Crisis intervention protocols for users expressing self-harm or serious depression', 'Professional referral systems for users requiring immediate mental health support', 'Confidentiality preservation while ensuring user safety', 'Specialized training for staff handling mental health data'] },
    { p: 'Crisis situations may require disclosure to emergency services or mental health authorities as permitted by law.', bold: true },
    { sub: '8.3 Cross-Border Data Transfers' },
    { p: 'International Service Providers: We transfer personal data outside India in accordance with Section 16 of the DPDP Act, 2023 (i.e., transfers are permitted except to countries restricted by Government notification). When we use international service providers, we ensure:' },
    { ul: ['Contractual, technical, and organizational safeguards for data protection', 'Standard Contractual Clauses where appropriate', 'User notification of any international data processing'] },

    { h: '9. Cookies and Tracking Technologies' },
    { sub: '9.1 Types of Tracking Technologies Used' },
    { p: 'Essential Technologies:', bold: true },
    { ul: ['Authentication tokens for secure login sessions', 'Security identifiers for fraud prevention and user verification', 'Session management for platform functionality', 'Load balancing for optimal performance'] },
    { p: 'Mobile App SDKs and Analytics:', bold: true },
    { ul: ['Usage analytics SDKs to understand app performance and feature adoption', 'Crash reporting SDKs to identify and resolve technical issues', 'Performance monitoring SDKs for optimization', 'Device identifiers for personalization and security (with opt-out available)'] },
    { p: 'Web-Based Cookies:', bold: true },
    { ul: ['Preference cookies for language, region, and interface settings', 'Analytics cookies for website usage statistics', 'Communication preference cookies for notification settings'] },
    { sub: '9.2 Managing Tracking Technologies' },
    { p: 'User Controls:', bold: true },
    { ul: ['Mobile app settings to control SDK permissions and data sharing', 'Device-level controls for advertising identifiers and app permissions', 'Browser settings to block or delete web cookies', 'Granular preferences in account settings for different tracking categories', 'Opt-out mechanisms for non-essential tracking technologies'] },
    { p: 'SDK and Device Identifier Management:', bold: true },
    { ul: ['Advertising ID controls through device settings (Android Advertising ID, Apple IDFA)', 'App permission management for location, camera, notifications', 'Third-party SDK opt-out where technically feasible'] },

    { h: '10. Updates to This Privacy Policy' },
    { sub: '10.1 Policy Changes' },
    { p: 'Types of Updates:', bold: true },
    { ul: ['Minor clarifications (effective immediately with notification)', 'Material changes affecting data processing (30-day notice period)', 'Legal compliance updates (as required by regulatory changes)', 'Feature additions requiring new consent (explicit consent required)'] },
    { sub: '10.2 Notification Methods' },
    { p: 'How We Notify You:', bold: true },
    { ul: ['Email notifications to your registered email address', 'In-app notifications prominently displayed upon login', 'Website banners highlighting policy changes', 'Push notifications for significant privacy-affecting changes'] },
    { p: 'Your Response Options:', bold: true },
    { ul: ['Continue using the Platform (indicating acceptance of changes)', 'Modify your privacy settings to reflect new preferences', 'Contact us with questions or concerns about changes', 'Delete your account if you disagree with material changes'] },

    { h: '11. Legal Basis and Compliance' },
    { sub: '11.1 Indian Data Protection Laws' },
    { p: 'Information Technology Act, 2000:', bold: true },
    { ul: ['Reasonable security practices implementation', 'Sensitive personal data protection measures', 'Data breach notification procedures', 'User consent management and documentation'] },
    { p: 'Digital Personal Data Protection Act, 2023:', bold: true },
    { ul: ['Lawful basis establishment for all data processing', 'Data Principal rights implementation and support', 'Consent management with clear and specific purposes', 'Cross-border transfer safeguards and limitations'] },
    { sub: '11.2 Healthcare Regulations' },
    { p: 'Clinical Establishments Act (where applicable):', bold: true },
    { ul: ['Healthcare service delivery standards and compliance', 'Patient information protection in clinical contexts', 'Professional service coordination within regulatory frameworks'] },
    { p: 'Telemedicine Guidelines, 2020:', bold: true },
    { ul: ['Digital consultation standards for healthcare provider interactions', 'Patient information security during telehealth services', 'Professional liability boundaries and user understanding'] },
    { sub: '11.3 Legal Basis for Processing' },
    { ul: ['Consent: Explicit consent for health data processing and marketing communications', 'Contract Performance: Account management, service delivery, payment processing', 'Legal Obligation: Regulatory compliance, tax requirements, legal requests', 'Legitimate Interest: Platform security, fraud prevention, service improvement', 'Vital Interest: Emergency health situations and crisis intervention'] },

    { h: '12. International Users' },
    { sub: '12.1 Service Availability' },
    { p: 'Geographic Limitations:', bold: true },
    { ul: ['Primary service area: India, with focus on Indian healthcare regulations', 'International access: Available but subject to local law compliance', 'Service modifications: May be limited in certain jurisdictions due to regulatory requirements', 'Currency and payments: Primarily INR, with limited international payment options'] },
    { sub: '12.2 Cross-Border Considerations' },
    { p: 'Data Processing:', bold: true },
    { ul: ["Indian data residency for Indian users' critical personal data", 'International service providers used with appropriate safeguards', 'Local law compliance responsibility for international users', 'Jurisdiction limitations for dispute resolution and legal processes'] },

    { h: '13. Contact Information and Data Protection' },
    { sub: '13.1 Privacy Inquiries' },
    { p: 'Data Protection Officer:', bold: true },
    { ul: ['Email: privacy@naricare.com', 'Address: ' + ADDRESS] },
    { p: 'Customer Support:', bold: true },
    { ul: ['Email: support@naricare.com', 'Phone (WhatsApp Business): +91-8142744762', 'Available: Monday-Saturday, 9 AM - 6 PM IST'] },
    { p: 'Grievance Officer (IT Rules, 2021):', bold: true },
    { ul: ['Name: Gayathri Devi Kanumuri', 'Email: grievance@naricare.com', 'Phone (WhatsApp Business): +91-8142744762', 'Address: ' + ADDRESS, 'Response: Within 24 hours (acknowledgment), 15 days (resolution)'] },
    { sub: '13.2 Complaint Resolution' },
    { p: 'Internal Process:', bold: true },
    { ol: ['Initial response within 72 hours of complaint receipt', 'Investigation completion within 30 days', 'Resolution communication with clear explanation of actions taken', 'Appeal process available for unsatisfactory resolutions'] },
    { p: 'Regulatory Complaints:', bold: true },
    { ul: ['Data Protection Board of India (DPB) (once operational)', 'Consumer Courts for service-related privacy disputes', 'CERT-In for cybersecurity-related complaints'] },
    { p: 'This Privacy Policy demonstrates our commitment to protecting your personal information while providing innovative maternal and infant health services. We continuously review and update our practices to ensure the highest standards of privacy protection.', bold: true },
    { p: 'For immediate privacy assistance, please contact privacy@naricare.com or use the privacy settings in your NariCare account.' }
  ]
};

export const TERMS_OF_SERVICE: LegalDoc = {
  title: 'Terms of Service',
  dates: ['Effective Date: October 15, 2025'],
  blocks: [
    { h: '1. Acceptance of Terms' },
    { p: 'These Terms of Service are a legally binding agreement between you ("User") and Sagex (NariCare). They govern your use of the NariCare platform, including our mobile app, website, and related services.' },
    { h: '2. Platform Description' },
    { p: 'NariCare operates a digital health platform specializing in maternal and infant care. Features include AI-powered educational support, professional consultations, health tracking, community support, and educational resources.' },
    { h: '3. Critical Disclaimers' },
    { ul: ['The Platform does not provide medical services or treatment. AI responses are educational only and not medical advice. For health concerns, consult licensed healthcare providers.', 'No doctor-patient relationship is created by using the Platform.', 'Do not use for emergencies. Dial 112 (or 108/102) or visit the nearest healthcare facility.', 'Always consult qualified healthcare providers for medical decisions.'] },
    { h: '4. User Eligibility and Registration' },
    { ul: ['Accounts must be created by persons 18+. Child profiles (<18) may be added with verifiable parental consent.', 'Registration details must be accurate and updated as necessary.', 'Users are responsible for account security and unauthorized use.'] },
    { h: '5. Services and Pricing' },
    { ul: ['Programs include app use, consultations, structured programs, and community forums.', 'Fees are in INR and subject to GST (GSTIN: 37AESFS8348M1ZV). Tax invoices issued.', 'Payment due in advance. Refunds: full refund if cancelled before program start; pro-rata refund for unused sessions if cancelled after start. Refunds processed within 7 days.'] },
    { h: '6. Intellectual Property' },
    { p: 'All platform content, including software, designs, logos, and AI models, are owned by Sagex or licensors. Users are granted a limited license for personal, non-commercial use only.' },
    { h: '7. User Conduct' },
    { p: 'Users must comply with laws. Prohibited conduct includes false information, impersonation, interference with security, harassment, reverse engineering, or unlawful/harmful content.' },
    { h: '8. Privacy and Data Protection' },
    { p: 'Use of the Platform is governed by our Privacy Policy (https://www.naricare.com/privacy-policy). By using tracking features, you consent to processing of sensitive health data as described in the Privacy Policy and under Indian law.' },
    { h: '9. Professional Services Disclaimer' },
    { p: 'Healthcare professionals are independent practitioners complying with the Telemedicine Guidelines, 2020 (identity, consent, and documentation). They maintain independent liability insurance. NariCare acts as a facilitator only and is not liable for clinical outcomes.' },
    { h: '10. Limitation of Liability' },
    { p: 'Platform provided "as is". No warranties. Liability capped at INR 50,000 or amount paid in last 12 months. Not liable for indirect, incidental, or consequential damages.' },
    { h: '11. Indemnification' },
    { p: 'Users agree to indemnify and hold harmless Sagex, its officers, employees, and agents from claims, damages, or expenses arising from misuse or breach of these Terms.' },
    { h: '12. Termination' },
    { p: 'We may suspend or terminate accounts for breaches, fraud, harmful conduct, or non-payment. Refunds as per Section 5. Programs terminate on completion of specified duration.' },
    { h: '13. Dispute Resolution' },
    { ul: ['Governing Law: India, Andhra Pradesh jurisdiction.', 'Non-exclusive jurisdiction: Courts of Visakhapatnam. Consumers may approach consumer fora.', 'Arbitration: Users may opt for arbitration under the Arbitration and Conciliation Act, 1996 (as amended), for disputes above INR 1,00,000. Arbitration optional; consumer rights preserved.'] },
    { h: '14. Regulatory Compliance' },
    { p: 'We comply with: Telemedicine Guidelines, 2020; MoHFW EHR Standards, 2016; Clinical Establishments Act, 2010 (where applicable); IT Act, 2000 and Rules; and DPDP Act, 2023 (with oversight by the Data Protection Board of India, once operational).' },
    { h: '15. Modifications' },
    { p: 'We may modify these Terms with notice. Material changes communicated via email, app notifications, and website banners. Continued use constitutes acceptance of revised Terms.' },
    { h: '16. Miscellaneous' },
    { p: 'If any provision is unenforceable, remaining provisions continue in force. We are not liable for force majeure. Terms may not be assigned by User without consent. Terms and Privacy Policy form the entire agreement.' },
    { h: '17. Grievance Redressal' },
    { p: 'Grievance Officer (IT Rules, 2021):', bold: true },
    { ul: ['Name: Gayathri Devi Kanumuri', 'Email: grievance@naricare.com', 'Phone/WhatsApp: +91-8142744762', 'Address: ' + ADDRESS, 'Response: acknowledgment within 24 hours, resolution within 15 days.'] },
    { h: '18. Contact Information' },
    { ul: ['Customer Support: support@naricare.com | Phone: +91-8142744762 | Mon-Sat, 9 AM-6 PM IST', 'Legal Notices: ' + ADDRESS + ' | legal@naricare.com'] }
  ]
};
